C# Web/ASP.NET Fundamentals - September 2024/Exam Preparation/Exam - GameZone/GameZone/Controllers/GameController.cs
using System.Globalization;
using System.Security.Claims;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using GameZone.Data;
using GameZone.Data.Models;
using GameZone.Models.Game;

using static GameZone.Constants.ModelsValidationConstants;

namespace GameZone.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        private readonly GameZoneDbContext dbContext;

        public GameController(GameZoneDbContext dbContext)
            => this.dbContext = dbContext;

        public IActionResult All()
        {
            var games = this.dbContext.Games
                .Where(x => !x.IsDeleted)
                .Select(x => new AllGameViewModel
                {
                    Id = x.Id,
                    Title = x.Title,
                    ImageUrl = x.ImageUrl,
                    ReleasedOn = x.ReleasedOn.ToString(GameReleasedOnDateFormat) ?? string.Empty,
                    Genre = x.Genre.Name,
                    Publisher = x.Publisher.UserName,
                })
                .AsNoTracking()
                .ToList();

            return View(games);
        }

        public IActionResult Add()
        {
            var model = new GameFormModel();
            model.Genres = this.GetAllGenres();

            return View(model);
        }

        [HttpPost]
        public IActionResult Add(GameFormModel formModel)
        {
            if (!ModelState.IsValid)
            {
                return View(formModel);
            }

            var isReleaseDateValid = DateTime.TryParseExact(formModel.ReleasedOn, GameReleasedOnDateFormat,
                CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime releasedOnDate);

            if (!isReleaseDateValid)
            {
                ModelState.AddModelError(nameof(formModel.ReleasedOn), "Invalid date format.");

                return View(formModel);
            }

            var game = new Game
            {
                Title = formModel.Title,
                Description = formModel.Description,
                ImageUrl = formModel.ImageUrl,
                PublisherId = this.GetCurrentUserId(),
                ReleasedOn = releasedOnDate,
                GenreId = formModel.GenreId,
                IsDeleted = false,
            };

            this.dbContext.Games.Add(game);
            this.dbContext.SaveChanges();

            return this.RedirectToAction("All");
        }

        public IActionResult Edit(int id)
        {
            var gameById = this.dbContext.Games
                .Where(x => x.Id == id && !x.IsDeleted)
                .Select(x => new GameFormModel
                {
                    Title = x.Title,
                    Description = x.Description,
                    ImageUrl = x.ImageUrl,
                    ReleasedOn = x.ReleasedOn.ToString(GameReleasedOnDateFormat),
                    GenreId = x.GenreId,
                })
                .FirstOrDefault();

            if (gameById != null)
            {
                gameById.Genres = this.GetAllGenres();
            }

            return this.View(gameById);
        }

        [HttpPost]
        public IActionResult Edit(GameFormModel formModel, int id)
        {
            if (!ModelState.IsValid)
            {
                return View(formModel);
            }

            var isReleaseDateValid = DateTime.TryParseExact(formModel.ReleasedOn, GameReleasedOnDateFormat,
                CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime releasedOnDate);

            if (!isReleaseDateValid)
            {
                ModelState.AddModelError(nameof(formModel.ReleasedOn), "Invalid date format.");

                return View(formModel);
            }

            var gameById = this.GetGameById(id);

            if (gameById.PublisherId != this.GetCurrentUserId())
            {
                return this.RedirectToAction("All");
            }

            gameById.Title = formModel.Title;
            gameById.Description = formModel.Description;
            gameById.ImageUrl = formModel.ImageUrl;
            gameById.PublisherId = this.GetCurrentUserId();
            gameById.ReleasedOn = releasedOnDate;
            gameById.GenreId = formModel.GenreId;
            gameById.IsDeleted = false;

            this.dbContext.SaveChanges();

            return this.RedirectToAction("All");
        }

        public IActionResult MyZone()
        {
            var games = this.dbContext.Games
                .Where(x => !x.IsDeleted && x.GamersGames.Any(y => y.GamerId == this.GetCurrentUserId()))
                .Select(x => new AllGameViewModel
                {
                    Id = x.Id,
                    Title = x.Title,
                    ImageUrl = x.ImageUrl,
                    ReleasedOn = x.ReleasedOn.ToString(GameReleasedOnDateFormat) ?? string.Empty,
                    Genre = x.Genre.Name,
                    Publisher = x.Publisher.UserName,
                })
                .AsNoTracking()
                .ToList();

            return this.View(games);
        }

        public IActionResult AddToMyZone(int id)
        {
            var currentUserId = this.GetCurrentUserId();
            var gameById = this.dbContext.Games
                .Where(x => x.Id == id)
                .Include(x => x.GamersGames)
                .FirstOrDefault();

            if (gameById == null || gameById.IsDeleted)
            {
                throw new ArgumentException("Invalid id.");
            }

            if (!gameById.GamersGames.Any(x => x.GameId == id && x.GamerId == currentUserId))
            {
                gameById.GamersGames.Add(new GamerGame
                {
                    GameId = id,
                    GamerId = currentUserId,
                });

                this.dbContext.SaveChanges();
            }
           
            return this.RedirectToAction("MyZone");
        }

        public IActionResult StrikeOut(int id)
        {
            var currentUserId = this.GetCurrentUserId();
            var gameById = this.dbContext.Games
                .Where(x => x.Id == id)
                .Include(x => x.GamersGames)
                .FirstOrDefault();

            if (gameById == null || gameById.IsDeleted)
            {
                throw new ArgumentException("Invalid id.");
            }

            if (gameById.GamersGames.Any(x => x.GameId == id && x.GamerId == currentUserId))
            {
                var gamerGame = gameById.GamersGames
                    .Where(x => x.GameId == id && x.GamerId == currentUserId)
                    .First();

                gameById.GamersGames.Remove(gamerGame);
                this.dbContext.SaveChanges();
            }

            return this.RedirectToAction("MyZone");
        }

        public IActionResult Details(int id)
        {
            var gameById = this.dbContext.Games
                .Where(x => x.Id == id && !x.IsDeleted)
                .Select(x => new DetailsGameViewModel
                {
                    Id = x.Id,
                    Title = x.Title,
                    Description = x.Description,
                    ImageUrl = x.ImageUrl,
                    ReleasedOn = x.ReleasedOn.ToString(GameReleasedOnDateFormat),
                    Publisher = x.Publisher.UserName,
                    Genre = x.Genre.Name,
                })
                .FirstOrDefault();

            if (gameById == null)
            {
                throw new ArgumentException("Invalid id.");
            }

            return this.View(gameById);
        }

        public IActionResult Delete(int id)
        {
            var gameByIdModel = this.dbContext.Games
                .Where(x => x.Id == id && !x.IsDeleted && x.PublisherId == this.GetCurrentUserId())
                .Select(x => new DeleteGameViewModel
                {
                    Id = x.Id,
                    Title = x.Title,
                    Publisher = x.Publisher.UserName,
                })
                .FirstOrDefault();

            if (gameByIdModel == null)
            {
                throw new ArgumentException("Invalid id.");
            }

            return this.View(gameByIdModel);
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(DeleteGameViewModel deleteModel)
        {
            var gameById = this.GetGameById(deleteModel.Id);

            gameById.IsDeleted = true;
            this.dbContext.SaveChanges();

            return this.RedirectToAction("All");
        }

        private string GetCurrentUserId()
            => this.User.FindFirstValue(ClaimTypes.NameIdentifier) ?? string.Empty;

        private List<Genre> GetAllGenres()
            => this.dbContext.Genres.AsNoTracking().ToList();

        private Game GetGameById(int id)
        {
            var gameById = this.dbContext.Games.Find(id);
            if (gameById == null || gameById.IsDeleted)
            {
                throw new ArgumentException("Invalid id.");
            }

            return gameById;
        }
    }
}

C# Web/ASP.NET Fundamentals - September 2024/Exam Preparation/Exam - GameZone/GameZone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameZone</title>
    <link rel="icon" type="image/x-icon" href="~/icons8-gameboy-gradient-32.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/custom-styles.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameZone.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameZone</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item mx-2">
                                <a class="nav-link btn btn-sm custom-button-color text-dark" asp-area="" asp-controller="Game" asp-action="All">Hall of Games</a>
                            </li>
                            <li class="nav-item mx-2">
                                <a class="nav-link btn btn-sm custom-button-color text-dark" asp-area="" asp-controller="Game" asp-action="Add">Blast Game</a>
                            </li>
                            <li class="nav-item mx-2">
                                <a class="nav-link btn btn-sm custom-button-color text-dark" asp-area="" asp-controller="Game" asp-action="MyZone">My Zone</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - GameZone
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>