C# Web/ASP.NET Advanced - October 2024/CarRentingSystem/CarRentingSystem/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

using AutoMapper;

using CarRentingSystem.Models.Cars;
using CarRentingSystem.Services.Cars.Contracts;
using CarRentingSystem.Services.Dealers.Contracts;
using CarRentingSystem.Infrastructure.Extensions;

using static CarRentingSystem.WebConstants;

namespace CarRentingSystem.Controllers
{
    public class CarsController : Controller
    {
        private readonly ICarsService carsService;
        private readonly IDealersService dealersService;
        private readonly IMapper mapper;

        public CarsController(ICarsService carsService, IDealersService dealersService, IMapper mapper)
        {
            this.carsService = carsService;
            this.dealersService = dealersService;
            this.mapper = mapper;
        }

        public IActionResult All([FromQuery]AllCarsQueryModel queryModel)
        {
            var queryResult = this.carsService.All(
                queryModel.Make,
                queryModel.SearchTerm,
                queryModel.Sorting,
                AllCarsQueryModel.CarsPerPage,
                queryModel.CurrentPage, 
                true);

            var carMakes = this.carsService.GetAllMakes();

            queryModel.Cars = queryResult.Cars;
            queryModel.TotalCars = queryResult.TotalCars;
            queryModel.Makes = carMakes;

            return this.View(queryModel);
        }

        public IActionResult Details(int id, string information)
        {
            var car = this.carsService.Details(id);

            if (car.GetInformation() != information)
            {
                return this.BadRequest();
            }

            return this.View(car);
        }

        [Authorize]
        public IActionResult Mine()
        {
            var myCars = this.carsService.ByUser(this.User.GetId());

            return this.View(myCars);
        }

        [Authorize]
        public IActionResult Create() 
        {
            if (!this.dealersService.IsDealer(this.User.GetId()) && !this.User.IsAdmin())
            {
                return this.RedirectToAction("Create", "Dealers");
            }

            return this.View(new CarFormModel
            {
                Categories = this.carsService.GetAllCategories(),
            });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(CarFormModel car)
        {
            var dealerId = this.dealersService.GetIdByUser(this.User.GetId());

            if (!dealerId.HasValue)
            {
                return this.RedirectToAction("Create", "Dealers");
            }

            if (!this.carsService.CategoryExists(car.CategoryId))
            {
                ModelState.AddModelError(nameof(car.CategoryId), "Category does not exist.");
            }

            if (!ModelState.IsValid)
            {
                car.Categories = this.carsService.GetAllCategories();

                return this.View(car);
            }

            var carId = this.carsService.Create(
                car.Make,
                car.Model,
                car.Description,
                car.ImageUrl,
                car.Year,
                car.CategoryId,
                dealerId.Value);

            this.TempData[GlobalMessageKey] = "You created a car successfully!";

            return this.RedirectToAction("Details", new { id = carId, information = car.GetInformation() });
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = this.User.GetId();

            if (!this.dealersService.IsDealer(userId) && !this.User.IsAdmin())
            {
                return this.RedirectToAction("Create", "Dealers");
            }

            var car = this.carsService.Details(id);
            if (car.UserId != userId && !this.User.IsAdmin())
            {
                return this.Unauthorized();
            }

            var carForm = this.mapper.Map<CarFormModel>(car);
            carForm.Categories = this.carsService.GetAllCategories();

            return this.View(carForm);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(int id, CarFormModel car)
        {
            var dealerId = this.dealersService.GetIdByUser(this.User.GetId());

            if (!dealerId.HasValue && !this.User.IsAdmin())
            {
                return this.RedirectToAction("Create", "Dealers");
            }

            if (!this.carsService.CategoryExists(car.CategoryId))
            {
                ModelState.AddModelError(nameof(car.CategoryId), "Category does not exist.");
            }

            if (!ModelState.IsValid)
            {
                car.Categories = this.carsService.GetAllCategories();

                return this.View(car);
            }

            if (this.dealersService.GetIdByUser(this.User.GetId()) != dealerId.Value && !this.User.IsAdmin())
            {
                return this.BadRequest();
            }

            var carIsEdited = this.carsService.Edit(
                id,
                car.Make,
                car.Model,
                car.Description,
                car.ImageUrl,
                car.Year,
                car.CategoryId,
                dealerId.Value,
                this.User.IsAdmin());

            if (!carIsEdited)
            {
                return this.BadRequest();
            }

            this.TempData[GlobalMessageKey] = "You edited a car successfully!";

            return this.RedirectToAction("Details", new { id = id, information = car.GetInformation() });
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            var dealerId = this.dealersService.GetIdByUser(this.User.GetId());

            if (!dealerId.HasValue && !this.User.IsAdmin())
            {
                return this.RedirectToAction("Create", "Dealers");
            }

            var carIsDeleted = this.carsService.Delete(id);

            if (!carIsDeleted)
            {
                return this.BadRequest();
            }

            return this.RedirectToAction("All");
        }
    }
}

C# Web/ASP.NET Advanced - October 2024/CarRentingSystem/CarRentingSystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

using AutoMapper;

using CarRentingSystem.Services.Cars.Contracts;
using CarRentingSystem.Services.Cars;

namespace CarRentingSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMapper mapper;
        private readonly IMemoryCache memoryCache;
        private readonly ICarsService carsService;

        public HomeController(IMapper mapper, IMemoryCache memoryCache, ICarsService carsService)
        {
            this.mapper = mapper;
            this.memoryCache = memoryCache;
            this.carsService = carsService;
        }

        public IActionResult Index()
        {
            const string latestCarsCacheKey = "latestCarsCacheKey";

            var latestCars = this.memoryCache.Get<List<CarServiceModel>>(latestCarsCacheKey);
            if (latestCars == null)
            {
                latestCars = this.carsService
                    .Latest()
                    .ToList();

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetSlidingExpiration(TimeSpan.FromMinutes(20));

                this.memoryCache.Set(latestCarsCacheKey, latestCars, cacheOptions);
            }

            return this.View(latestCars);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() => this.View();
    }
}

C# Web/ASP.NET Advanced - October 2024/CarRentingSystem/CarRentingSystem/Views/Home/Index.cshtml
@model ICollection<CarServiceModel>

@{
    ViewData["Title"] = "Home Page";
    var isFirst = true;
}

@if (!Model.Any())
{
    <div class="jumbotron">
        <h1 class="display-4">Welcome to the best car renting site!</h1>
        <p class="lead">There are no any available cars in the system right now.</p>
        <hr class="my-4">        
        <p class="lead">
            <a asp-controller="Cars" asp-action="Create" class="btn btn-primary btn-lg" role="button">Create a Car</a>
        </p>
    </div>
}

@if (Model.Any())
{
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
        @foreach (var car in Model)
        {
            <div class="carousel-item @(isFirst ? "active" : "")">
                <img class="d-block mx-auto carousel-img" src="@car.ImageUrl" alt="@car.Make @car.Model - (@car.Year @car.CategoryName)">
                <div class="carousel-caption d-none d-md-block">
                        <h5><a class="btn btn-primary" asp-controller="Cars" asp-action="Details" asp-route-id="@car.Id" asp-route-information="@car.GetInformation()">@car.Make @car.Model (@car.Year)</a></h5>
                </div>
            </div>

            isFirst = false;
        }
        </div>
        <a class="carousel-control-prev carousel-btn" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next carousel-btn" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="row">
        <div class="col-12 text-center">
            <button class="btn btn-warning mt-4" id="statistics-button">Show Statistics</button>
        </div>
    </div>

    <div class="jumbotron d-none mt-4" id="statistics">
        <div class="row">
            <h2 class="col-md-4 text-center" id="total-cars"></h2>
            <h2 class="col-md-4 text-center" id="total-users"></h2>
            <h2 class="col-md-4 text-center" id="total-rents"></h2>
        </div>
    </div>
}

@section Scripts {
    <script>
        $('#statistics-button').on('click', e => {
            $.get('/api/statistics', (data) => {
                $('#total-cars').text(data.totalCars + " Cars");
                $('#total-users').text(data.totalUsers + " Users");
                $('#total-rents').text(data.totalRents + " Rents");
                
                $('#statistics').removeClass('d-none');
                $('#statistics-button').hide();
            });
        });
    </script>
}